// <auto-generated />
namespace LYF_BLOG.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addusernamecoloumonusertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addusernamecoloumonusertable));
        
        string IMigrationMetadata.Id
        {
            get { return "201605230939055_Add username coloum on user table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
